name: hr_mobile_app
description: "Comprehensive HR Mobile Application for Sri Lankan IT Companies with Flutter and Firebase"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  firebase_remote_config: ^5.1.3
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # Navigation
  go_router: ^14.6.1
  
  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Location & QR
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  # qr_code_scanner: ^1.0.1 # Temporarily disabled due to Android build issue
  qr_flutter: ^4.1.0
  
  # PDF & Documents
  pdf: ^3.11.1
  printing: ^5.13.2
  file_picker: ^8.1.2
  
  # Network & HTTP
  http: ^1.2.2
  dio: ^5.7.0
  connectivity_plus: ^6.0.5
  
  # Image & Media
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  image_cropper: ^8.0.2
  
  # Utilities
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  
  # Charts & Analytics
  fl_chart: ^0.69.0
  
  # Biometric Authentication
  local_auth: ^2.3.0
  
  # Calendar
  table_calendar: ^3.1.2
  
  # Phone Number
  phone_numbers_parser: ^8.3.0
  
  # Encryption
  crypto: ^3.0.5
  
  # Validation
  form_validator: ^2.1.1
  
  # Local Notifications
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/data/
  
  fonts:
    - family: Noto Sans Sinhala
      fonts:
        - asset: assets/fonts/NotoSansSinhala-Regular.ttf
    - family: Noto Sans Tamil
      fonts:
        - asset: assets/fonts/NotoSansTamil-Regular.ttf
