// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5THKOknwQRxvjVCCCa8fYfCpH_37GVXw',
    appId: '1:444168307043:web:5bc557902f9a04d7f69356',
    messagingSenderId: '444168307043',
    projectId: 'hrms-mobile-app-e1066',
    authDomain: 'hrms-mobile-app-e1066.firebaseapp.com',
    storageBucket: 'hrms-mobile-app-e1066.firebasestorage.app',
    measurementId: 'G-YPDLQVFMD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYYooxj4wSB5un4ciGIUtwbOxPqCAlyUU',
    appId: '1:444168307043:android:40395feab0dea5ecf69356',
    messagingSenderId: '444168307043',
    projectId: 'hrms-mobile-app-e1066',
    storageBucket: 'hrms-mobile-app-e1066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKu7WUu_ZotdhWjrLOP2u9Nt3Il57ociU',
    appId: '1:444168307043:ios:1fb61babaffbf309f69356',
    messagingSenderId: '444168307043',
    projectId: 'hrms-mobile-app-e1066',
    storageBucket: 'hrms-mobile-app-e1066.firebasestorage.app',
    iosBundleId: 'com.srilanka.hrapp.hrMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKu7WUu_ZotdhWjrLOP2u9Nt3Il57ociU',
    appId: '1:444168307043:ios:1fb61babaffbf309f69356',
    messagingSenderId: '444168307043',
    projectId: 'hrms-mobile-app-e1066',
    storageBucket: 'hrms-mobile-app-e1066.firebasestorage.app',
    iosBundleId: 'com.srilanka.hrapp.hrMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5THKOknwQRxvjVCCCa8fYfCpH_37GVXw',
    appId: '1:444168307043:web:98ba8b19d5ba6c57f69356',
    messagingSenderId: '444168307043',
    projectId: 'hrms-mobile-app-e1066',
    authDomain: 'hrms-mobile-app-e1066.firebaseapp.com',
    storageBucket: 'hrms-mobile-app-e1066.firebasestorage.app',
    measurementId: 'G-VHFBQ7YZCV',
  );
}
